---
title: Jekyll Portfolio
timezone: UTC
collections:
  experiments:
    title: Experiments
    output: true
    permalink: "/experiments/:path/"
  posts:
    title: Posts
    output: true
  presentations:
    title: Presentations
    output: true
    permalink: "/speaking/:path/"
  category:
      title: category
      output: true
      permalink: "/category/:path/"
  uploads:
    title: Uploads
    output: true
name: Bryan Robinson - Design Strategist and Front-end Developer
author: Bryan Robinson
author_email: bryanlrobinson@gmail.com
url: http://bryanlrobinson.com/
permalink: "/blog/:year/:month/:day/:title/"
markdown: kramdown
highlight_options:
  linenos: true
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
