name: Bryan Robinson - Design Strategist and Front-end Developer

author: Bryan Robinson

author_email: bryanlrobinson@gmail.com

category_dir: /blog

collections:
    presentations:
        output: true
        permalink: /speaking/:path/


url: http://bryanlrobinson.com/

permalink: pretty

exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
