name: Bryan Robinson - Design Strategist and Front-end Developer

author: Bryan Robinson

author_email: bryanlrobinson@gmail.com

category_dir: /blog

url: http://bryanlrobinson.com/

collections:
    experiments:
        output: true
        permalink: /experiments/:path/

permalink: pretty

exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
