name: Bryan Robinson - Design Strategist and Front-end Developer

author: Bryan Robinson

author_email: bryanlrobinson@gmail.com

collections:
    presentations:
        output: true
        permalink: /speaking/:path/
    experiments:
        output: true
        permalink: /experiments/:path/

url: http://bryanlrobinson.com/

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown

highlight_options:
  linenos: true


exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
