name: Bryan Robinson - Design Strategist and Front-end Developer

author: Bryan Robinson

author_email: bryanlrobinson@gmail.com

collections:
    presentations:
        output: true
        permalink: /speaking/:path/


url: http://bryanlrobinson.com/

permalink: /blog/:year/:month/:day/:title/

exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
